name: testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  test-linux:
    runs-on: ubuntu-24.04
    steps:
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: checkout repository
        uses: actions/checkout@v7
      - name: install dependencies
        run: |
          pip install onnxruntime && \
          pip install -r requirements.txt && \
          pip install pytest
      - name: patch version
        run: |
          chmod u+x ./releng/patch_version.sh && \
          ./releng/patch_version.sh
      - name: test version
        run: cat ./graxpert/version.py
      - name: Run tests
        run: python -m pytest --import-mode=append tests/

  test-windows:
    runs-on: windows-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: checkout repository
        uses: actions/checkout@v7
      - name: install dependencies
        run: |
          pip install onnxruntime; `
          pip install -r requirements.txt; `
          pip install pytest
      - name: patch version
        run: ./releng/patch_version.ps1
      - name: test version
        run: type ./graxpert/version.py
      - name: Run tests
        run: python -m pytest --import-mode=append tests/

  test-macos-arm64:
    runs-on: macos-14
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: install dependencies
        run: |
          brew install python-tk && \
          pip3 install onnxruntime --break-system-packages && \
          pip3 install -r requirements.txt --break-system-packages && \
          pip3 install pytest --break-system-packages
      - name: patch version
        run: |
          chmod u+x ./releng/patch_version.sh && \
          ./releng/patch_version.sh
      - name: Run tests
        run: python3 -m pytest --import-mode=append tests/

  test-macos-x86_64:
    runs-on: macos-15-intel
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: install dependencies
        run: |
          brew install python-tk && \
          pip3 install "onnxruntime<=1.23.2" --break-system-packages && \
          pip3 install -r requirements.txt --break-system-packages && \
          pip3 install pytest --break-system-packages
      - name: patch version
        run: |
          chmod u+x ./releng/patch_version.sh && \
          ./releng/patch_version.sh
      - name: Run tests
        run: python3 -m pytest --import-mode=append tests/
